{{- if and .Values.externalSecrets .Values.externalSecrets.secretsEnabled }}
{{- $namespace := .Values.global.namespace | default "default" }}
{{- $secretStoreName := .Values.externalSecrets.secretStoreName }}

{{- /* Simple secrets - single key per secret */}}
{{- range $secret := .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.secretName }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ $secret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ $secret.secretKey }}
      remoteRef:
        key: {{ $secret.secretID }}
        version: latest
{{- end }}

{{- /* Multi-key secrets - multiple keys in a single secret */}}
{{- range $secret := .Values.externalSecrets.multiKeySecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.secretName }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ $secret.secretName }}
    creationPolicy: Owner
  data:
    {{- range $data := $secret.data }}
    - secretKey: {{ $data.secretKey }}
      remoteRef:
        key: {{ $data.secretID }}
        version: latest
    {{- end }}
{{- end }}

{{- end }}
