{{- if .Values.golemPostgres.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: golem-postgres-initsql
  namespace: default
data:
  init.sql: |
    -- shared libraries for extensions
    ALTER SYSTEM SET
    shared_preload_libraries = pg_parquet,pg_stat_statements,auto_explain;

    ALTER SYSTEM SET
    max_connections = '5000';
    ALTER SYSTEM SET
    shared_buffers = '16GB';
    ALTER SYSTEM SET
    effective_cache_size = '48GB';
    ALTER SYSTEM SET
    maintenance_work_mem = '3GB';
    ALTER SYSTEM SET
    checkpoint_completion_target = '0.9';
    ALTER SYSTEM SET
    wal_buffers = '16MB';
    ALTER SYSTEM SET
    default_statistics_target = '500';
    ALTER SYSTEM SET
    random_page_cost = '1.1';
    ALTER SYSTEM SET
    effective_io_concurrency = '200';
    ALTER SYSTEM SET
    work_mem = '209kB';
    ALTER SYSTEM SET
    huge_pages = 'try';
    ALTER SYSTEM SET
    min_wal_size = '4GB';
    ALTER SYSTEM SET
    max_wal_size = '16GB';
    ALTER SYSTEM SET
    max_worker_processes = '16';
    ALTER SYSTEM SET
    max_parallel_workers_per_gather = '8';
    ALTER SYSTEM SET
    max_parallel_workers = '16';
    ALTER SYSTEM SET
    max_parallel_maintenance_workers = '4';

    CREATE DATABASE IF NOT EXISTS airis_objects;
    \connect airis_objects
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS pg_parquet;
    CREATE TYPE source AS ENUM ('OPEN_VOCABULARY', 'CLOSED_VOCABULARY');

    CREATE TABLE IF NOT EXISTS objects (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            airis_pipeline_id VARCHAR NOT NULL,
            object_id UUID NOT NULL,
            frame_name VARCHAR NOT NULL,
            source source NOT NULL,
            bbox VECTOR(4) NOT NULL,
            class_embedding VECTOR(513),
            class_embedder VARCHAR NOT NULL,
            visual_embedding VECTOR(768),
            visual_embedder VARCHAR NOT NULL,
            description_embedding VECTOR(512),
            description_embedder VARCHAR NOT NULL,
            class_name VARCHAR,
            start_time VARCHAR NOT NULL,
            end_time VARCHAR NOT NULL,
            cluster_id VARCHAR NOT NULL,
            classification_confidence FLOAT,
            config_version INTEGER NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            PRIMARY KEY (id),
            UNIQUE (object_id)
    )

    ;
    CREATE INDEX objects_class_embedding_idx ON objects USING hnsw (class_embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
    CREATE INDEX objects_description_embedding_idx ON objects USING hnsw (description_embedding vector_ip_ops) WITH (m = 16, ef_construction = 64);
    CREATE INDEX objects_config_version_idx ON objects (config_version);
    CREATE INDEX objects_created_at_idx ON objects (created_at);
    CREATE INDEX objects_class_name_idx ON objects (class_name);
    CREATE INDEX objects_visual_embedding_idx ON objects USING hnsw (visual_embedding vector_ip_ops) WITH (m = 16, ef_construction = 64);

    CREATE DATABASE IF NOT EXISTS airis_poi;
    \connect airis_poi
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS pg_parquet;
    CREATE TYPE quality AS ENUM ('TRASH', 'NON_RECOGNIZABLE', 'RECOGNIZABLE');
    CREATE TYPE representation AS ENUM ('REPRESENTATIVE', 'NON_REPRESENTATIVE');

    CREATE TABLE IF NOT EXISTS faces (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            local_id VARCHAR NOT NULL,
            global_id UUID NOT NULL,
            airis_pipeline_id VARCHAR NOT NULL,
            embedding VECTOR(512) NOT NULL,
            quality quality NOT NULL,
            quality_score FLOAT NOT NULL,
            representation representation NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            PRIMARY KEY (id)
    )

    ;
    CREATE INDEX poi_faces_embedding_vector_idx ON faces USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
    CREATE INDEX poi_faces_embedding_vector_partial_representative_idx ON faces USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64) WHERE representation = 'REPRESENTATIVE' AND quality = 'RECOGNIZABLE';
    CREATE INDEX poi_faces_local_id_idx ON faces (local_id);
    CREATE INDEX poi_faces_global_id_idx ON faces (global_id);
    CREATE INDEX poi_faces_airis_pipeline_id_idx ON faces (airis_pipeline_id);

    CREATE TABLE IF NOT EXISTS faces_metadata (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            face_id BIGINT NOT NULL,
            video_name VARCHAR NOT NULL,
            frame_number INTEGER NOT NULL,
            x1 INTEGER NOT NULL,
            y1 INTEGER NOT NULL,
            x2 INTEGER NOT NULL,
            y2 INTEGER NOT NULL,
            thumbnail_path VARCHAR,
            PRIMARY KEY (id),
            UNIQUE (face_id),
            FOREIGN KEY(face_id) REFERENCES faces (id) ON DELETE CASCADE
    )

    ;
    CREATE INDEX poi_faces_metadata_face_id_idx ON faces_metadata (face_id);

    CREATE DATABASE IF NOT EXISTS airis_voice;
    \connect airis_voice
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS pg_parquet;

    CREATE TABLE speaker (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            airis_pipeline_id VARCHAR NOT NULL,
            speaker_id VARCHAR NOT NULL,
            embedding VECTOR(192),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            PRIMARY KEY (id)
    )

    ;
    CREATE INDEX speaker_embedding_idx ON speaker USING hnsw (embedding vector_l2_ops) WITH (m = 16, ef_construction = 64);
    CREATE INDEX speaker_created_at_idx ON speaker (created_at);
    CREATE INDEX speaker_airis_pipeline_id_speaker_id_idx ON speaker (airis_pipeline_id, speaker_id);
{{- end}}
