{{- if .Values.appwrite.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "redis"
spec:
  ports:
    - port: {{ .Values.appwrite.redis.servicePort }}
      targetPort: {{ .Values.appwrite.redis.servicePort }}
  selector:
    app: "appwrite"
  type: ClusterIP
{{- end }}
