{{- if and .Values.nats.enabled .Values.nats.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Values.global.namespace }}
  selector:
    matchLabels:
      app: nats
{{- end }}
